Check UpdatedNumberScheduled on DaemonSet apply
k14s/kapp pull request #211
Opened 2021-04-16 18:32 UTC by acosta11

When updating cf-for-k8s on a GKE cluster, we observe unexpectedly fast daemonset reconciliation. And after kapp returns successful, we observe daemonset pods continuing to roll. There appears to be a race condition between the pod scheduler and kapp's number unavailable pod check on daemonset update which returns successful if kapp checks the state of the daemonset before the first pod is deleted as part of the update.

To mitigate this, we've added a check for the number of updated pods scheduled on the IsDoneApplying function for daemonsets.

Thanks,
Andrew and @davewalter

2021-05-05 15:32 UTC, joaopapereira requested changes
Hey the PR looks good.
We are in the process of using testify to replace our hand rolled assertions, do you mind changing the tests to match that?
Instead of
```go
       if state != expectedState {
		t.Fatalf("Found incorrect state: %#v", state)
	}
```

Have:
```go
require.Equal(t, expectedState, state)
```

2021-05-05 15:33 UTC, joaopapereira commented
@acosta11 can you also, please sign the CLA?

2021-05-05 16:33 UTC, acosta11 commented
> Hey the PR looks good.
> We are in the process of using testify to replace our hand rolled assertions, do you mind changing the tests to match that?
> Instead of
> 
> ```go
>        if state != expectedState {
> 		t.Fatalf("Found incorrect state: %#v", state)
> 	}
> ```
> 
> Have:
> 
> ```go
> require.Equal(t, expectedState, state)
> ```

Sounds good, we can make those updates.

> @acosta11 can you also, please sign the CLA?

Dave and I requested membership to the vmware-tanzu org but do not seem to have it yet. Will see if we can get that request moving again.

2021-05-14 17:14 UTC, acosta11 commented
Oops, may have just axed my branch diff while getting up to date with develop. Re-opening now with the requested changes now that I'm in the vmware-tanzu org to pass the cla check.

Thanks,
Andrew

2021-05-28 13:31 UTC, joaopapereira approved these changes
LGTM

2021-05-28 14:52 UTC, merged